# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  fr: Accueil
  de: Home
email: 
description:
  fr: Titulaire du master CAWEB (création et animation de sites web multilingues), je suis actuellement à la recherche d’un poste en tant que graphiste. 
  de: Als Inhaber des Masters CAWEB (Erstellung und Animation mehrsprachiger Websites) bin ich derzeit auf der Suche nach einer Stelle als Mediengestalter. 
index:
  fr: index.html
  de: home.html
feed:
  fr: /flux.xml
  de: /feed.xmls
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
